//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.26 at 06:08:09 PM MSK 
//


package travel_20190326.storage.loadinitialdata.xjc;

import travel_20190326.storage.loadinitialdata.xjc.City;
import travel_20190326.storage.loadinitialdata.xjc.Country;
import travel_20190326.storage.loadinitialdata.xjc.InitData;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xjc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xjc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InitData }
     * 
     */
    public InitData createInitData() {
        return new InitData();
    }

    /**
     * Create an instance of {@link Country }
     * 
     */
    public Country createCountry() {
        return new Country();
    }

    /**
     * Create an instance of {@link InitData.Countries }
     * 
     */
    public InitData.Countries createInitDataCountries() {
        return new InitData.Countries();
    }

    /**
     * Create an instance of {@link City }
     * 
     */
    public City createCity() {
        return new City();
    }

    /**
     * Create an instance of {@link Country.Cities }
     * 
     */
    public Country.Cities createCountryCities() {
        return new Country.Cities();
    }

}
